### ISSUE TITLE
in-app without newsstand ?

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#475] opened 2015-06-06 20:49 UTC
hI!
My app is up and running, using my cloud console server. cool. 

Now I wonder if I could remove my app from newsstand and keep the in-app purchase working ?
I don't care about subscriptions, and just want my app to be an app with a shelf where people can buy books, not issues and subscriptions.

So to sum it up : can I get a newsstand baker app working out of newstand, at the cost of loosing the subscription stuff, but keeping the in-app purchase and cloud console system ?

**Comment by tobiasstrebitzer** [comment] 2015-06-12 09:01
Closing, this is a duplicate of #470 - Standalone App with ability to download new issues

**Closed by tobiasstrebitzer** 2015-06-12 09:01 UTC
